//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendGrid.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailDetail
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string TimeStamp { get; set; }
        public string C_event { get; set; }
        public string response { get; set; }
        public string category { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string URL { get; set; }
        public string IP { get; set; }
        public string smtp_id { get; set; }
    }
}
